export const initProjects: MyTypes.Project[] = [
  {
    id: 1,
    name: "翠湖公寓",
    address: "南京市·江宁区",
    floors: 4,
    buildingType: "住宅",
    description: "依湖而居，绿意环绕，享受宁静生活的每一天",
  },
  {
    id: 2,
    name: "锦绣花园",
    address: "南京市·江宁区",
    floors: 6,
    buildingType: "住宅",
    description: "优美景致，尽享奢华，锦绣花园让您回归自然之美",
  },
  {
    id: 3,
    name: "阳光驿站",
    address: "南京市·江宁区",
    floors: 6,
    buildingType: "住宅",
    description: "阳光普照，温暖之家，您的生活从此光彩夺目",
  },
  {
    id: 4,
    name: "蓝湾公馆",
    address: "南京市·雨花台区",
    floors: 16,
    buildingType: "住宅",
    description: "蓝天碧海，繁华尽享，蓝湾公馆为您开启理想生活",
  },
  {
    id: 5,
    name: "御景台",
    address: "南京市·鼓楼区",
    floors: 12,
    buildingType: "住宅",
    description: "尊贵典雅，景致非凡，御景台让您的生活更上一层楼",
  },
  {
    id: 6,
    name: "星辰苑",
    address: "南京市·江宁区",
    floors: 6,
    buildingType: "住宅",
    description: "繁星点点，宁静夜晚，星辰苑为您打造梦幻家园",
  },
  {
    id: 7,
    name: "枫林小筑",
    address: "南京市·江宁区",
    floors: 22,
    buildingType: "住宅",
    description: "四季如画，温馨小筑，枫林小筑带您体验自然之美",
  },
];
